# --- Datasource
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=${POSTGRES_URL}
quarkus.datasource.username=${POSTGRES_USER}
quarkus.datasource.password=${POSTGRES_PASSWORD}

# --- Flyway
quarkus.flyway.migrate-at-start=true
quarkus.flyway.baseline-on-migrate=true

# --- Redis
quarkus.redis.hosts=${REDIS_HOST}
quarkus.redis.password=${REDIS_PASSWORD}

# --- Server
quarkus.http.port=${QUARKUS_API_PORT}