# --- Datasource
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=${POSTGRES_URL}
quarkus.datasource.username=${POSTGRES_USER}
quarkus.datasource.password=${POSTGRES_PASSWORD}

# --- Flyway
quarkus.flyway.migrate-at-start=true
quarkus.flyway.baseline-on-migrate=true

# --- Redis
quarkus.redis.hosts=${REDIS_HOST}
quarkus.redis.password=${REDIS_PASSWORD}

# --- Server
quarkus.http.port=${QUARKUS_API_PORT}

# --- Security Validation
smallrye.jwt.verify.key.location=publicKey.pem
smallrye.jwt.sign.key.location=${JWT_SIGN_KEY_LOCATION}
smallrye.jwt.verify.issuer=${QUARKUS_API_URL}

# --- Security CORS
quarkus.http.cors=true
quarkus.http.cors.origin=${CLIENT_URL}
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=Content-Type,Authorization
quarkus.http.cors.access-control-allow-credentials=true

# --- Security Cookies
quarkus.http.auth.cookie.cookie-name=accessToken
quarkus.http.auth.cookie.enabled=true
smallrye.jwt.token.header=Cookie
