"""add_event_fee_status_and_claim_token_target

Revision ID: 41c5dbd21364
Revises: 73993d44b85f
Create Date: 2026-08-22 13:06:57.690956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41c5dbd21364'
down_revision: Union[str, Sequence[str], None] = '73993d44b85f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_events', sa.Column('status', sa.Enum('PENDING_FEE', 'ACTIVE', 'CANCELLED', 'FINISHED', name='eventstatus', native_enum=False), nullable=False))
    op.add_column('tb_events', sa.Column('service_fee', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('tb_events', sa.Column('ticket_title', sa.String(length=100), nullable=False))
    op.add_column('tb_events', sa.Column('ticket_description', sa.Text(), nullable=True))
    op.add_column('tb_events', sa.Column('sales_start_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tb_events', sa.Column('sales_end_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tb_events', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('tb_events', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('tb_events', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.drop_index(op.f('idx_events_state_city'), table_name='tb_events')
    op.create_index(op.f('ix_tb_events_organizer_id'), 'tb_events', ['organizer_id'], unique=False)
    op.add_column('tb_users', sa.Column('pending_balance', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_users', 'pending_balance')
    op.drop_index(op.f('ix_tb_events_organizer_id'), table_name='tb_events')
    op.create_index(op.f('idx_events_state_city'), 'tb_events', ['state', 'city_slug'], unique=False)
    op.alter_column('tb_events', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('tb_events', 'updated_at')
    op.drop_column('tb_events', 'created_at')
    op.drop_column('tb_events', 'sales_end_at')
    op.drop_column('tb_events', 'sales_start_at')
    op.drop_column('tb_events', 'ticket_description')
    op.drop_column('tb_events', 'ticket_title')
    op.drop_column('tb_events', 'service_fee')
    op.drop_column('tb_events', 'status')
    # ### end Alembic commands ###
