"""create_event_payouts_table

Revision ID: 57ee2d1c3d28
Revises: 41c5dbd21364
Create Date: 2026-08-22 18:23:43.665396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57ee2d1c3d28'
down_revision: Union[str, Sequence[str], None] = '41c5dbd21364'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_event_payouts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('organizer_id', sa.Uuid(), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('platform_fee_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'PAID', 'FAILED', name='payoutstatus', native_enum=False), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['tb_events.id'], ),
    sa.ForeignKeyConstraint(['organizer_id'], ['tb_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_event_payouts')
    # ### end Alembic commands ###
