"""extend_wallet_claim_tokens_type_and_target

Revision ID: 73993d44b85f
Revises: 937110025084
Create Date: 2026-08-21 21:52:29.461400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '73993d44b85f'
down_revision: Union[str, Sequence[str], None] = '937110025084'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_wallet_claim_tokens', sa.Column('type', sa.Enum('DEPOSIT', 'TICKET_PURCHASE', 'EVENT_FEE', name='claimtype', native_enum=False), nullable=False))
    op.add_column('tb_wallet_claim_tokens', sa.Column('target_id', sa.Uuid(), nullable=True))
    op.alter_column('tb_wallet_claim_tokens', 'status',
               existing_type=postgresql.ENUM('PENDING', 'CLAIMED', 'EXPIRED', name='claimtokenstatus'),
               type_=sa.Enum('PENDING', 'CLAIMED', 'EXPIRED', name='claimtokenstatus', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tb_wallet_claim_tokens', 'status',
               existing_type=sa.Enum('PENDING', 'CLAIMED', 'EXPIRED', name='claimtokenstatus', native_enum=False),
               type_=postgresql.ENUM('PENDING', 'CLAIMED', 'EXPIRED', name='claimtokenstatus'),
               existing_nullable=False)
    op.drop_column('tb_wallet_claim_tokens', 'target_id')
    op.drop_column('tb_wallet_claim_tokens', 'type')
    # ### end Alembic commands ###
