"""create_tb_wallet_claim_tokens_table

Revision ID: 937110025084
Revises: 99d44f8c0e2c
Create Date: 2026-08-21 20:12:44.447938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '937110025084'
down_revision: Union[str, Sequence[str], None] = '99d44f8c0e2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_wallet_claim_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('token', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CLAIMED', 'EXPIRED', name='claimtokenstatus'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['tb_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_wallet_claim_tokens_token'), 'tb_wallet_claim_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_tb_wallet_claim_tokens_user_id'), 'tb_wallet_claim_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tb_wallet_claim_tokens_user_id'), table_name='tb_wallet_claim_tokens')
    op.drop_index(op.f('ix_tb_wallet_claim_tokens_token'), table_name='tb_wallet_claim_tokens')
    op.drop_table('tb_wallet_claim_tokens')
    # ### end Alembic commands ###
