"""create tb wallet transactions table

Revision ID: 99d44f8c0e2c
Revises: d8d35cdb8d3a
Create Date: 2026-08-21 12:02:00.185514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99d44f8c0e2c'
down_revision: Union[str, Sequence[str], None] = 'd8d35cdb8d3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_wallet_transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('DEPOSIT', 'TICKET_PURCHASE', 'TICKET_REFUND', 'EVENT_CREATION_FEE', 'EVENT_PAYOUT', name='transactiontype', native_enum=False), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=True),
    sa.Column('ticket_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['tb_events.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tb_tickets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['tb_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_wallet_tx_user_type', 'tb_wallet_transactions', ['user_id', 'type'], unique=False)
    op.create_index(op.f('ix_tb_wallet_transactions_type'), 'tb_wallet_transactions', ['type'], unique=False)
    op.add_column('tb_users', sa.Column('balance', sa.DECIMAL(precision=10, scale=2), server_default='0.00', nullable=False))
    op.add_column('tb_users', sa.Column('image_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_users', 'image_url')
    op.drop_column('tb_users', 'balance')
    op.drop_index(op.f('ix_tb_wallet_transactions_type'), table_name='tb_wallet_transactions')
    op.drop_index('idx_wallet_tx_user_type', table_name='tb_wallet_transactions')
    op.drop_table('tb_wallet_transactions')
    # ### end Alembic commands ###
