"""update event model

Revision ID: d4b9faa85507
Revises: ad939757e301
Create Date: 2026-08-20 20:13:27.981160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4b9faa85507'
down_revision: Union[str, Sequence[str], None] = 'ad939757e301'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_events', sa.Column('location_url', sa.String(), nullable=True))
    op.add_column('tb_events', sa.Column('poster_url', sa.String(), nullable=True))
    op.alter_column('tb_events', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('tb_events', 'total_capacity')
    op.drop_column('tb_events', 'external_api_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_events', sa.Column('external_api_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('tb_events', sa.Column('total_capacity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('tb_events', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('tb_events', 'poster_url')
    op.drop_column('tb_events', 'location_url')
    # ### end Alembic commands ###
