"""improve events location and images customization

Revision ID: d8d35cdb8d3a
Revises: 1d783ce48902
Create Date: 2026-08-21 06:08:40.896766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8d35cdb8d3a'
down_revision: Union[str, Sequence[str], None] = '1d783ce48902'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_events', sa.Column('location_name', sa.String(length=150), nullable=False))
    op.add_column('tb_events', sa.Column('cep', sa.String(length=9), nullable=False))
    op.add_column('tb_events', sa.Column('address', sa.String(length=255), nullable=False))
    op.add_column('tb_events', sa.Column('number', sa.String(length=20), nullable=False))
    op.add_column('tb_events', sa.Column('neighborhood', sa.String(length=100), nullable=False))
    op.add_column('tb_events', sa.Column('city', sa.String(length=100), nullable=False))
    op.add_column('tb_events', sa.Column('city_slug', sa.String(length=100), nullable=False))
    op.add_column('tb_events', sa.Column('state', sa.String(length=2), nullable=False))
    op.add_column('tb_events', sa.Column('complement', sa.String(length=100), nullable=True))
    op.add_column('tb_events', sa.Column('custom_image_url', sa.String(length=500), nullable=True))
    op.add_column('tb_events', sa.Column('maps_url', sa.String(length=500), nullable=True))
    op.create_index('idx_events_state_city', 'tb_events', ['state', 'city_slug'], unique=False)
    op.create_index(op.f('ix_tb_events_city_slug'), 'tb_events', ['city_slug'], unique=False)
    op.drop_column('tb_events', 'location_url')
    op.drop_column('tb_events', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_events', sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('tb_events', sa.Column('location_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_tb_events_city_slug'), table_name='tb_events')
    op.drop_index('idx_events_state_city', table_name='tb_events')
    op.drop_column('tb_events', 'maps_url')
    op.drop_column('tb_events', 'custom_image_url')
    op.drop_column('tb_events', 'complement')
    op.drop_column('tb_events', 'state')
    op.drop_column('tb_events', 'city_slug')
    op.drop_column('tb_events', 'city')
    op.drop_column('tb_events', 'neighborhood')
    op.drop_column('tb_events', 'number')
    op.drop_column('tb_events', 'address')
    op.drop_column('tb_events', 'cep')
    op.drop_column('tb_events', 'location_name')
    # ### end Alembic commands ###
