services:
  db:
    image: postgres:16-alpine
    container_name: vzticket_db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${database_user}
      POSTGRES_PASSWORD: ${database_password}
      POSTGRES_DB: ${database_name}
    ports:
      - "${database_port}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${database_user} -d ${database_name}"]
      interval: 5s
      timeout: 5s
      retries: 5
