[project]
name = "api"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.19.1",
    "asyncpg>=0.31.0",
    "fastapi[standard]>=0.141.1",
    "pwdlib[argon2]>=0.3.1",
    "pyjwt>=2.13.0",
    "sqlalchemy>=2.0.52",
]

[dependency-groups]
dev = [
    "aiosqlite>=0.22.1",
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "pytest-cov>=7.1.0",
    "ruff>=0.16.3",
    "taskipy>=1.14.1",
]

[tool.ruff]
line-length = 88
indent-width = 4
extend-exclude = ['migrations']

[tool.ruff.format]
quote-style = 'single'
indent-style = 'space'

[tool.ruff.lint]
preview = true
select = ['I', 'F', 'E', 'W', 'PL', 'PT', 'FAST']

[tool.pytest.ini_options]
pythonpath = '.'
addopts = '-p no:warnings'
asyncio_mode = 'auto'

[tool.taskipy.tasks]
lint = 'ruff check --fix'
test = 'pytest --cov=verzel -vv'
post_test = 'coverage html'
run = 'fastapi dev verzel/main.py'
